### PR TITLE
improving clarity

### PR DESCRIPTION
**Pull request by fatmaf**
The bit about creating a topological map was a little confusing - added a line or two to make it clearer.

### CODE REVIEW

**Comment by hawesie** [comment]
Thanks, much appreciated.

**Comment by hawesie** [comment]
@heuristicus please could you update the docs from this? I have 2fa on my github account so the the script you wrote for doing the updates doesn't work for me.

**Comment by heuristicus** [comment]
The docs update only has to be run if you want to retrieve all the repository readmes etc from scratch, which in this case isn't necessary since we're changing something in this repository. The readthedocs framework checks this repository so any changes to master should be reflected in the webpage. I just checked and it's working as expected.

**Comment by hawesie** [comment]
Awesome, thanks.

**Pull request merged**
